Enhancement: add thinkpad_acpi module
home-assistant/operating-system pull request #1388
Opened 2021-06-01 16:03 UTC by herrfrei

The thinkpad_acpi module is needed to adjust the battery charge thresholds (see [tlp homepage](https://linrunner.de/tlp/faq/battery.html)) 
when using a newer Thinkpad laptop (T430(s)/T530/W530/X230 and all later) for hassos.

2021-06-01 16:03 UTC, homeassistant commented
Hi @herrfrei, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;operating-system#1388).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-06-04 13:18 UTC, agners requested changes

2021-06-04 13:18 UTC, agners commented on buildroot-external/board/pc/generic-x86-64/kernel.config
> +# Lenovo Thinkpad ACPI module
This seems obvious from the name, so:

```suggestion
```

2021-06-04 13:19 UTC, agners commented
How do you change the threshold then? I mean, we don't have provisions in HAOS to change it. Are there reasonable defaults when the module is loaded?

2021-06-04 13:35 UTC, herrfrei commented
Changing these values requires writing to `/sys/class/power_supply/BATx/charge_start_threshold` and `/sys/class/power_supply/BATx/charge_stop_threshold`. BATx might be BAT0, BAT1, ...

I'm not sure what the default values are, may be they differ between devices.

2021-06-05 13:15 UTC, agners approved these changes

2021-06-05 13:16 UTC, merged