Add support RTL88x2BU usb wifi dongles
home-assistant/operating-system pull request #1742
Opened 2022-02-08 06:55 UTC by kyangk

This pull request adds support for RTL88x2BU usb wifi dongles.

Package source is from `https://github.com/cilynx/rtl88x2bu`

I have personally tested RTL8812BU on my rpi3b+ running Homeassistant OS 32bit w/ `Kangzio USB WiFi Adapter 1300Mbps`.

```
# lsmod
Module                  Size  Used by
88x2bu               2338816  0
rfcomm                 49152  4
nf_conntrack_netlink    49152  0
nfnetlink              16384  2 nf_conntrack_netlink
...
```

```
# ./iwconfig
...
wlan1     IEEE 802.11AC  ESSID:"REDACTED"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:5.785 GHz  Access Point: REDACTED
          Bit Rate:867 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:****-****-****-****-****-****-****-****   Security mode:open
          Power Management:off
          Link Quality=77/100  Signal level=70/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

Some other example hardware (from searching web)
```
Fastoe AC1200 USB Wi-Fi Adapter
Cudy WU1200 AC1200 High Gain USB Wi-Fi Adapter
TP-Link Archer T3U
TP-Link Archer T3U Plus
TP-Link Archer T4U V3
Linksys WUSB6400M
Dlink DWA-181
Dlink DWA-182
```

2022-02-08 06:55 UTC, homeassistant commented
Hi @kyangk, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;operating-system#1742).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-02-08 10:15 UTC, agners reviewed
Can you also add the driver to generic-x86-64, khadas-vim3, and the odroids?

2022-02-08 10:15 UTC, agners commented on buildroot-external/package/rtl88x2bu/Config.in
> +	  Help message of RTL88X2BU
```suggestion
	  Driver for RTL88X2BU USB WiFi adapters (no firmware needed).
```

2022-02-09 07:36 UTC, kyangk commented
All the other added platforms compiled successfully. I have no way of actually testing them beyond this.

2022-02-11 21:33 UTC, kyangk commented
Anything else I should do for this to merge?

2022-02-21 16:29 UTC, agners requested changes

2022-02-21 16:29 UTC, agners commented on buildroot-external/package/rtl88x2bu/Config.in
> +
```suggestion
```

2022-02-21 16:32 UTC, merged

2022-03-25 20:27 UTC, diegomontanaduarte commented
@agners When this merge will be available on rel-7 branch?

2022-03-28 07:42 UTC, agners commented
Currently I don't intend to backport it to rel-7. rel-8 will soon enter rc phase. Also, you can install nightly builds already (https://os-builds.home-assistant.io/), it will be possible to upgrade to rc/stable builds.

2022-04-01 11:01 UTC, diegomontanaduarte commented
@agners any ETA for rel-8 stable release?

2022-04-02 10:56 UTC, agners commented
I'll build a first rc next week or so, final release depends on how it goes... I hope in April still. We will see.

2022-04-02 11:18 UTC, diegomontanaduarte commented
@agners Niceeeeee! Thanks for your prompt response on all my questions!