Add support for AArch64/ARM64 EFI architecture
home-assistant/operating-system pull request #1757
Opened 2022-02-21 15:25 UTC by Doridian

This uses GRUB because Barebox does not support ARM64 and the only supported bootloader by BR2 seems to be GRUB for this scenario.

I had to use `qemuarm-64` in several places as machine type as `generic-aarch64` versions of some containers (namely supervisor) do not exist and/or work correctly.

I have done basic functionality testing with `rauc`
- The current partition gets marked as good, HA seems to start up correctly
- I can swap partition to B, but of course as I cannot create update packages it does not boot, but it does get selected and then (correctly) fail to boot

2022-02-21 15:25 UTC, homeassistant commented
Hi @Doridian, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;operating-system#1757).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-02-21 16:35 UTC, agners commented on .github/workflows/matrix.json
> +    "runner": "aarch64-64-runner",
```suggestion
   "runner": "aarch64-runner",
```

2022-02-21 16:43 UTC, agners commented
Hm, there is a limitation in our PR dev build infrastructure: We can only build for machines which already exist in the `dev` branch (since that is where the metadata are coming from to create the build matrix).

Anyways, I will create a build locally, should be a quick thing.

2022-02-21 19:25 UTC, agners commented
@Doridian uploaded the builds to the root of https://os-builds.home-assistant.io/.

Can you share the qemu command line options you are using to test the images?

2022-02-21 19:26 UTC, Doridian commented
@agners I attached my QEMU test script to the initial post, completely forgot to do that initially.

2022-02-21 23:04 UTC, agners commented
It seems that installing the raucb currently fails:

```sh
rauc install haos_generic-aarch64-8.0.dev20220221.raucb
...
LastError: Installation error: Failed updating slot boot.0: failed to run slot hook: Child process exited with code 1
```

We assume that there is a txt file in the root and back it up. Because there is no txt, the rauc hook `buildroot-external/ota/rauc-hook` fails. You can work around by just adding a `cmdline.txt`:

```sh
touch /mnt/boot/cmdline.txt
```

Which brings up another question: Can we add that file (can be empty for now) and make its content append to the kernel boot arguments? Might be not really Grub standard of doing things, but would align nicely with the other platforms.

2022-02-21 23:07 UTC, agners requested changes
It seems that a barebox file gets copied to /etc currently. Can you adjust the if statement at `buildroot-external/scripts/rauc.sh:install_bootloader_config` as well to accommodate the new `BOOTLOADER` value (just check explicitly for barebox).

2022-02-21 23:17 UTC, agners commented on buildroot-external/board/generic-aarch64/grub.cfg
> +}
I guess technically that is not even necessary is it? It would fallback to the first entry which is A as well..?

2022-02-22 00:01 UTC, Doridian commented
@agners
For your points:

The third boot option:
I have adjusted the GRUB config to allow removing the third boot option (it was initially necessary due to the RAUC config template necessitating a difference between "unselected, default to A" and "selected, use A" profiles, but i circumnavigated that with a default of 99, which is surely invalid and can be used as a flag)

The cmdline.txt
I have not found a way in GRUB to read an arbitrary file into a variable at all. I can "source" a file, I can load the env file, and I can exec a file. But I have not seen a way to load a plain text file
Therefor I have made the cmdline.txt that format (`set CMDLINE="...."`), so it can be updated as all the other versions do, but with a slightly modified format.

2022-02-22 10:19 UTC, agners requested changes

2022-02-22 10:19 UTC, agners commented on buildroot-external/board/generic-aarch64/cmdline.txt
> +set CMDLINE="rootwait zram.enabled=1 zram.num_devices=3 apparmor=1 security=apparmor systemd.machine_id=$MACHINE_ID cgroup_enable=memory fsck.repair=yes"
This should only contain boot arguments which the user should adjust. For now I would leave it empty. Also, I think set is not strictly necessary correct? Can this be:

```suggestion
cmdline=""
```

2022-02-22 10:19 UTC, agners commented on buildroot-external/board/generic-aarch64/grub.cfg
> +source ($root)/cmdline.txt
I then would add the default args here:

```suggestion
default_cmdline="rootwait zram.enabled=1 zram.num_devices=3 apparmor=1 security=apparmor systemd.machine_id=$MACHINE_ID cgroup_enable=memory fsck.repair=yes"
source ($root)/cmdline.txt
```

2022-02-22 10:19 UTC, agners commented on buildroot-external/board/generic-aarch64/grub.cfg
> +    linux (${boothd},gpt2)/Image root=PARTUUID=8d3d53e3-6d49-4c38-8349-aff6859e82fd $CMDLINE rauc.slot=A
```suggestion
    linux (${boothd},gpt2)/Image root=PARTUUID=8d3d53e3-6d49-4c38-8349-aff6859e82fd $default_cmdline $cmdline rauc.slot=A
```

2022-02-22 10:19 UTC, agners commented on buildroot-external/board/generic-aarch64/grub.cfg
> +    linux (${boothd},gpt4)/Image root=PARTUUID=a3ec664e-32ce-4665-95ea-7ae90ce9aa20 $CMDLINE rauc.slot=B
```suggestion
    linux (${boothd},gpt4)/Image root=PARTUUID=a3ec664e-32ce-4665-95ea-7ae90ce9aa20 $default_cmdline $cmdline rauc.slot=B
```

2022-02-22 10:19 UTC, agners commented on buildroot-external/board/generic-aarch64/kernel.config
> +
This seems to come from generic-x86-64. Lots in here is quite Intel specific and probably will never be seen on a aarch64 platform.

I'd suggest to go with something like this:

```
CONFIG_EFI_STUB=y

CONFIG_VIRTIO=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_BALLOON=m
CONFIG_VIRTIO_INPUT=m
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_BLK_SCSI=y
CONFIG_VIRTIO_CONSOLE=m
CONFIG_VIRTIO_VSOCKETS=m
CONFIG_VIRTIO_MMIO=y
CONFIG_SCSI_VIRTIO=y
CONFIG_HW_RANDOM_VIRTIO=y

CONFIG_DRM_VIRTIO_GPU=m
```

2022-02-22 15:52 UTC, Doridian commented
@agners Your assumption about set being optional is correct. Implemented your suggestions, still boots in QEMU

2022-02-23 09:08 UTC, agners commented
Moved the new board to `buildroot-external/board/arm-uefi/` (just in case we introduce a dedicated machine for virtualization at one point).

Also added qcow2 and vdi disk images which are useful especially since the machine is mainly used for virtualization right now.

2022-02-23 09:10 UTC, agners approved these changes

2022-02-23 09:42 UTC, merged