Maintain and upload artifacts index
home-assistant/operating-system pull request #2839
Opened 2023-10-18 11:57 UTC by agners

Make the artifacts browsable by maintaining a list of builds. This keeps it up-to-date even when deleting images from the object storage, and minimizes queries to the object storage.

2023-10-18 14:10 UTC, ludeeus requested changes

2023-10-18 18:20 UTC, agners commented on .github/workflows/build.yaml
> +            --include "index.json" \
Hm, kinda annoying :cry:  Can't this be done with some cache control attribute? E.g. only force refresh if a browser forces refresh through cache control headers? :thinking:

2023-10-18 19:38 UTC, ludeeus commented on .github/workflows/build.yaml
> +            --include "index.json" \
Not reliably, but its a single file, jst bust it as a last step.

2023-10-19 08:18 UTC, agners commented on .github/workflows/build.yaml
> +            --include "index.json" \
I've added the cache flush. This requires secrets update still.

2023-10-19 08:18 UTC, agners commented on .github/os-artifacts/index.html
> +                    console.error('Error fetching images:', error);
Added error handling when response is not ok.

2023-10-26 12:18 UTC, ludeeus approved these changes

2023-10-26 18:24 UTC, merged