Fix rauc hook to restore machine-id in new grub environment
home-assistant/operating-system pull request #3451
Opened 2024-06-29 16:39 UTC by claplace

Without a machine-id, the next boot will be considered as a first boot, and any external data disk will be disabled.

Fixes #3247.

<img width="416" alt="Screenshot 2024-06-29 at 12 32 46" src="https://github.com/home-assistant/operating-system/assets/11894677/c01b434e-5013-4013-8fab-bc96d8e56fa5">

After installing my raucb update bundle and a reboot:

```
Jun 29 16:34:38 homeassistant kernel: Kernel command line: BOOT_IMAGE=(hd0,gpt4)/Image root=PARTUUID=a3ec664e-32ce-4665-95ea-7ae90ce9aa20 rootwait zram.enabled=1 zram.num_devices=3 systemd.machine_id=6c631b4986cb426f9b7860df4ce10629 fsck.repair=yes console=ttyS0 console=tty0 rauc.slot=B
```

The machine-id has been conserved 👍

2024-06-29 16:44 UTC, claplace commented
I'd like to add the `rel-x` label, but I'm not sure I can do that myself.

2024-07-03 13:36 UTC, sairon requested changes
Thanks for looking into this, you got it right. In fact, the same issue started to manifest in latest dev builds for OVA/x86 as a result of #3435. However, I'll prefer to do it differently - instead of amending the `grubenv` distributed in the update bundle, preserve it as whole - in the same way as we do with the `*.txt` files (which we use for persisting machine-id on non-grub platforms).

2024-07-03 23:32 UTC, claplace commented
Hi @sairon, that works even better, thank you!

<img width="403" alt="Screenshot 2024-07-03 at 19 30 05" src="https://github.com/home-assistant/operating-system/assets/11894677/cbcfc3a3-ce40-402c-bf5f-8c302be08f0b">

2024-07-04 08:13 UTC, sairon approved these changes
Looking good now, thank you!

2024-07-04 08:14 UTC, merged

2024-07-04 08:16 UTC, sairon commented
Tagging with generic-aarch64 only, since x86/OVA targets were not affected until the patch that landed just recently only in dev.